### PR TITLE
CA-358583: Fix PROXY metadata to multiple HTTPS requests on a connection

### LINKED ISSUE #4517: Bogus HTTP 403 errors after hotfix XS82E031 for valid HTTPS requests
The commits from PR #4422 not only block requests on port 80, but also some requests on port 443. After the attempt at debugging @benjamreis and I did, it looks like this happens for every subsequent request within the same TLS connection.

### How to reproduce (1)
From a web browser, load a web page that fetches various resources from the host such as JS or images. This is what XCP-ng's web page does ([sources](https://github.com/xcp-ng/xcp-ng-release/tree/master/src/xenserver/opt/xensource/www)):
image
Traces we added in the code showed most requests for resources were rejected with a 403 error.

This is what the page should look like:
image

### How to reproduce (2)
You can also reproduce what is probably another manifestation of the same issue on Citrix Hypervisor 8.2 with XS82E031 applied: just load the web page from the host with Firefox, and refresh, again and again. It should reject one of two requests: the first request succeeds (new TLS connection logged in secure.log). The next one fails (HTTP 403. secure.log shows the second request causes the TLS connection to be closed). Then the next one succeeds (new TLS connection opened in secure.log), the one after that fails, and so on.
One of us reproduced it in Chrome too, but others didn't unless they'd mash F5 fast enough, so that two queries overlap, maybe. I think that Firefox leaves the connection open for subsequent requests more eagerly than chrome does.

### What we found out so far
The main test to check for a valid TLS connection in XAPI is
```ocaml
let access_forbidden req s =
   (* Reject external non-TLS requests (depending on config) *)
   !Xapi_globs.website_https_only
   && (not (Context.is_unix_socket s))
   && Context._client_of_rq req = None
 ```
What plays a significant role here is `Context._client_of_rq req = None`, which only lets requests that pass `Context._client_of_rq req != None` through.

And the definition of `Context._client_of_rq` is:
 ```ocaml
let _client_of_rq rq =
  let stunnel_proxy =
    List.assoc_opt "STUNNEL_PROXY" rq.Http.Request.additional_headers
  in
  Option.bind stunnel_proxy (fun proxy ->
      try
        Scanf.sscanf proxy "TCP6 %s %s %d %d" (fun client _ _ _ -> client)
        |> _clean_addr_of_string
      with _ ->
        R.error "Failed to parse STUNNEL_PROXY='%s'" proxy ;
        None)
 ```
 
We have verified that `Context._client_of_rq req` was usually not None for the first request of a series, but was None for any other request made under the same TLS connection. Thus causing a rejection and the connection to be closed. Then, after the connection has been closed, the next one succeeds because we start again with a fresh connection and `Context._client_of_rq req` is not None.

We assume that either `Context._client_of_rq req` is not an appropriate test to check that the request came from a valid TLS connection, or `stunnel` does not set the appropriate headers (`STUNNEL_PROXY`?) for any request within a TLS connection that is not the first of the series.

### Addendum
I also tested what happens if I set `website-https-only` to `false` in `xapi.conf`. Then the page always loads correctly, as before, but the debug traces I had added showed that only the first request of a series would pass the `Context._client_of_rq req != None` test. When loading the same file successively as described in "How to reproduce (2)", I would get such behaviour visible in secure.log + xensource.log (output to the latter being my added traces):
```
secure.log: `Service [xapi] accepted connection from...`
xensource.log: fileserver.send_file: new request. Context._client_of_rq req != None
xensource.log: fileserver.send_file: new request. Context._client_of_rq req = None
xensource.log: fileserver.send_file: new request. Context._client_of_rq req = None
[...]
xensource.log: fileserver.send_file: new request. Context._client_of_rq req = None
xensource.log: fileserver.send_file: new request. Context._client_of_rq req = None
secure.log: `Connection closed`
secure.log: `Service [xapi] accepted connection from...`
xensource.log: fileserver.send_file: new request. Context._client_of_rq req != None
xensource.log: fileserver.send_file: new request. Context._client_of_rq req = None
xensource.log: fileserver.send_file: new request. Context._client_of_rq req = None
[etc.]
```
As I tried to illustrate with forged logs (mine are less readable), the first request after establishing the TLS connection passes the `Context._client_of_rq req != None` test but not any of the subsequent ones... Until the connection finally closes and a new one is established, starting a new similar series.

### PR DESCRIPTION
**Pull request by robhoes**
When stunnel is configured with `protocol = proxy`, it will send a PROXY
header right at the beginning after establishing a connection to the
server, before passing on any decrypted data from the client. This
header contains useful TCP parameters, such as the source IP (see
04dd088). Even if this connection ends up carrying multiple HTTP(S)
requests, there will only be one PROXY header sent, as stunnel doesn't
interpret the data.

The HTTP server, however, looks for the PROXY header and HTTP header in
one step. So the first request on the connection gets annotated with
this PROXY data, and any following requests on the same connection do
not. It doesn't remember that it had already seen the PROXY header. This
is easily fixed in the receive loop by passing on a PROXY header once
one has been seen.

Fixes: https://github.com/xapi-project/xen-api/issues/4517

Signed-off-by: Rob Hoes <rob.hoes@citrix.com>

### CODE REVIEW

**Comment by stormi** [comment]
I'll try to test it. Do you happen to already have a patch that would apply on 2.25.2? If not, I'll try to adapt it on monday for testing it.

**Comment by robhoes** [comment]
I've not backported it yet, but it should not be hard to get it to apply.

**Comment by stormi** [comment]
So, I tried to cherry-pick the commit on top of v2.25.2 and solved all the conflicts that are just due to formatting changes, but there remains one that is less straightforward:
image

How would you solve it?

**Comment by robhoes** [comment]
Just make it exactly like on `proxyfix`. It looks like `master` just had an additional minor refactor to remove uses of the `Opt` module.

**Comment by stormi** [comment]
Thanks. I've got a successful build now. Here's what the cherry-picked commit looks like after conflict solving: https://github.com/stormi/xen-api-libs-transitional/commit/a11d38b1d12f4f2e092d08e4f1579ad413556f7a

**Review by lindig — APPROVED** [review]

File: http-svr/http_svr.ml [hunk 1]
```diff
@@ -407,107 +407,120 @@ let request_of_bio_exn_slow ic =
...
 
 (** [request_of_bio_exn ic] reads a single Http.req from [ic] and returns it. On error
     	it simply throws an exception and doesn't touch the output stream. *)
 
-let request_of_bio_exn bio =
+let request_of_bio_exn ~proxy_seen bio =
   let fd = Buf_io.fd_of bio in
-  let frame, headers, proxy = Http.read_http_request_header fd in
+  let frame, headers, proxy' = Http.read_http_request_header fd in
+  let proxy = match proxy' with None -> proxy_seen | x -> x in
```
Comment (lindig) [inline http-svr/http_svr.ml:434]: This is the critical line - everything else is just decoration.

**Comment by stormi** [comment]
> Thanks. I've got a successful build now. Here's what the cherry-picked commit looks like after conflict solving: [stormi@a11d38b](https://github.com/stormi/xen-api-libs-transitional/commit/a11d38b1d12f4f2e092d08e4f1579ad413556f7a)

Tested in XCP-ng 8.2: this does fix the bogus HTTP 403 errors described in xapi-project/xen-api#4517

File: http-svr/http_svr.ml [hunk 2]
```diff
@@ -407,107 +407,120 @@ let request_of_bio_exn_slow ic =
...
+    ; task= !task
+    ; subtask_of= !subtask_of
+    ; content_type= !content_type
+    ; host= !host
+    ; user_agent= !user_agent
+    ; additional_headers= headers
+    ; accept= !accept
+    }
+  in
+  (request, None)
```
Comment (edwintorok) [inline http-svr/http_svr.ml:426]: Why None? can't we pass the proxy_seen through the same we do for request_of_bio on the fast path? I think we have the fast path turned off in quite a few places due to requirement to do file descriptor passing on some of xapi's sockets (and wanting to stop reading exactly where headers finish).

**Review by edwintorok — APPROVED** [review]
I think this is a good improvement over what we have now, we might have to plumb the proxy_seen through the slowpath as well, not just on the fastpath though.

File: http-svr/http_svr.ml (hunk 2 above)
Comment (robhoes) [reply http-svr/http_svr.ml:426]: The slow path doesn't have code at all yet for parsing the PROXY header, so it doesn't have this bug, and therefore it doesn't need this bug fix. Whether we need to add it to that path is a separate question (and patch).
